- name: group hosts by distribution
  hosts: all 
  gather_facts: True
  tasks:
    - name: create groups based on distro
      group_by: key={{ ansible_distribution }}

    - name: "{{ ansible_distribution  }}"
      debug: 
        msg: "{{ansible_all_ipv4_addresses}}: {{ ansible_distribution}}-{{ ansible_distribution_version }}"

